name: app_scala_quickstart_cli

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: olafurpg/setup-scala@v11
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: sbt-build
      run: sbt clean update compile
      
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: olafurpg/setup-scala@v11
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Run tests
      run: sbt test
      
  publish:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: olafurpg/setup-scala@v11
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: build, assemble and upload pipeline artifact
      run: sbt assembly
    - uses: actions/upload-artifact@v4
      with:
        name: app_scala_quickstart_cli
        path: release